#!/bin/bash -x
# Redis replication binding

WD="$HOME/Documents/Dev/repos/vrubiolo/rp-service-cloud/build"
REDIS="$HOME/Documents/Dev/repos/iotbzh/rp-service-hiredis/build"

if [[ "$1" == "debug" ]]; then
    GDB="gdb --args"
    #export AFB_DEBUG_BREAK=main-entry
fi

cd $WD
$GDB afb-daemon --name rp-cloud --port=5678 --workdir=$WD \
--ldpath=/dev/null --binding=package/lib/rp-cloud.so \
--roothttp=package/htdocs --token= --tracereq=common -vvv \
--ws-client=tcp:localhost:1212/redis-from-cloud \
--ws-client=unix:/tmp/redis \
--monitoring
