#!/bin/bash -x
# Redis replication binding

WD="$HOME/Documents/Dev/repos/iotbzh/cloud-publication-binding/build"
GDB_CMD="$HOME/Documents/Dev/repos/vrubiolo/rp-service-cloud/scripts/gdb-init"
REDIS="$HOME/Documents/Dev/repos/iotbzh/rp-service-hiredis/build"
GWEN_UI="$HOME/tmp/redpesk-marine/Web_binder_app/afb-ui-devtool/dist"

if [[ "$1" == "debug" ]]; then
    GDB="gdb -x $GDB_CMD --args"
    #export AFB_DEBUG_BREAK=main-entry
fi

cd $WD
# XXX: process name in getBinderName() truncates it to 17 chars!
$GDB afb-binder --name cloud-pub --port=5678 --workdir=$WD \
--binding=package/lib/cloud-publication.so \
--roothttp=$GWEN_UI \
--tracereq=common -vvv \
--ws-client=tcp:localhost:1212/redis-from-cloud \
--ws-client=unix:/tmp/redis \
--monitoring
