#!/bin/bash -x

WD="$HOME/Documents/Dev/repos/vrubiolo/rp-service-cloud/build"

afb-daemon --name rp-cloud --port=5678 --workdir=$WD \
--ldpath=/dev/null --binding=package/lib/rp-cloud.so \
--roothttp=package/htdocs --token= --tracereq=common -vvv \
